#!/bin/sh

# Check if .husky-ddev file exists to determine whether to use DDEV
if [ -f ".husky-ddev" ]; then
    echo "Detected .husky-ddev file, executing ddev npm run lint ..."
    ddev exec 'npm run lint'
else
    . "$(dirname "$0")/_/husky.sh"
    npm run lint
fi
